version: 2

jobs:
  build:
    docker:
      - image: docker:18.09-git

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
            version: 19.03.13

      - run: |
           docker build -t devdaniil/eureka_service ./
           docker login -u devdaniil -p 749e096e-cb17-414b-a4e7-6d052b521264
           docker push devdaniil/eureka_service
      
