
version: 2

jobs:
  build:
    docker:
      - image: docker:18.09-git

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: "Build Service Container by Dockerfile"
          command: docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ./

      - run:
          name: "Login in Docker"
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}

      - run:
          name: "Push service to Docker Hub"
          command: docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}

